RSTsite/urls.py
from django.conf.urls import url,include

from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('rst2html.urls')),
]

rst2html/urls.py
from django.conf.urls import url

from . import views

app_name = 'rst2html'
urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^Pview/$', views.Preview, name='Preview'),
    url(r'^save/$', views.save, name='save'),
    url(r'^uploadImagePage/$', views.uploadImagePage, name='uploadImagePage'),
    url(r'^uploadImage/$', views.uploadImage, name='uploadImage'),
    url(r'^$', views.clearUpload, name='clearUpload'),
]

rst2html/models.py
from django.db import models


class Image(models.Model):
    Image = models.FileField(upload_to='rst2html/static/rst2html/image')

rst2html/views.py
from django.shortcuts import render,HttpResponse,HttpResponseRedirect
import os
import sys
import datetime
import zipfile
from django.views.static import serve
from django.core.urlresolvers import reverse
from django.core.files.storage import default_storage
def home(request):


    dirPath = 'rst2html/static/rst2html/uploadImage/'
    context = {}
    imagelist = []
    for file in os.listdir(dirPath):
        filename,ext = os.path.splitext(file)
        if ext == '.jpg'or ext == '.png'or ext == '.gif':
            imagelist.append(filename+ext)
    context['imagelist'] = imagelist
    
    return render(request,'rst2html/workpage.html',context)

def clearUpload(request):
    
    dirPath = 'rst2html/static/rst2html/uploadImage/'
    imagelist = []
    for file in os.listdir(dirPath):
        filename,ext = os.path.splitext(file)
        os.remove('rst2html/static/rst2html/uploadImage/{}{}'.format(filename,ext))

    return render(request,'rst2html/workpage.html')
def Preview(request):
    textFile = open('rst2html/static/rst2html/inputText.rst','w')
    textFile.write(request.GET['myTextBox'])
    textFile.close()
    command = request.GET['style']
    os.system('rst2html5 '+command+' rst2html/static/rst2html/inputText.rst > rst2html/static/rst2html/output.html')

    htmlFile = open('rst2html/static/rst2html/{}.html'.format('output'), 'r')
    html_content = ""
    for item in htmlFile:
        html_content = html_content + item  # keep all string in html file
    htmlFile.close()
    os.remove('rst2html/static/rst2html/inputText.rst')  # remove rst file
    os.remove('rst2html/static/rst2html/{}.html'.format('output'))  # remove html file
    return HttpResponse(html_content)


def uploadImagePage(request):

    return render(request,'rst2html/uploadImagePage.html')

def uploadImage(request):
    file = request.FILES['pic']
    dirPath = 'rst2html/static/rst2html/uploadImage/'
    saveFilePath = default_storage.save(dirPath, file)
    os.rename(saveFilePath, '{}{}'.format(dirPath, file.name))

    return render(request,'rst2html/uploadImagePage.html')
    

def save(request):# remove html file
    SlideName = request.GET['SlideName']
    os.system('mkdir '+SlideName)
    textFile = open(SlideName+'/inputText.rst','w')
    textFile.write(request.GET['myTextBox'])
    textFile.close()
    command = request.GET['style']
    os.system('rst2html5 '+command+SlideName+'/inputText.rst > '+SlideName+'/output.html')
    with zipfile.ZipFile(SlideName+'.zip', 'w') as myzip:
        myzip.write(SlideName+'/inputText.rst')
        myzip.write(SlideName+'/output.html')
        os.system('rm -r '+SlideName)
    
    file_path  = SlideName+'.zip'

    response = HttpResponse(open(file_path, 'rb').read() , content_type='application/zip')
    response['Content-Disposition'] = 'attachment; filename='+file_path
    return response

rst2html/templates/rst2html/deck.html
<!DOCTYPE html><html><head><meta charset="utf-8"><title></title><style type="text/css">body{
 font-family: helvetica;
 color: #222;
}

li>p{
 margin-bottom: 0;
}

.line{
 margin-bottom: 0.3em;
 display: table;
}

.admonition-title {
    font-size: 1.3em;
    font-weight: bold;
}

aside{
 float: right;
 width: 20%;
 display: table;
 padding: 1em;
 margin: 1em;
 margin-right: 0;
}

.footnote, .cite{
 width: 98%;
 display: table;
 border: 1px solid #ddd;
 padding: 0.5%;
 margin: 0.5%;
}

.footnote .du-label, .cite .du-label{
 float: left;
 height: 100%;
 width: 5%;
 margin-right: 1em;
 padding: 0.5%;
 text-align: center;
 display: table;
}

th, th p{
 font-weight: bold;
}

.field-label{
 font-weight: bold;
}

ol.arabic{
 list-style-type: decimal;
}

ol.loweralpha{
 list-style-type: lower-alpha;
}

ol.upperalpha{
 list-style-type: upper-alpha;
}

ol.lowerroman{
 list-style-type: lower-roman;
}

ol.upperroman{
 list-style-type: upper-roman;
}

img.align-left{
 float: left;
}

img.align-right{
 float: right;
}
</style></head><body></body></html>

rst2html/templates/rst2html/output.html
<!DOCTYPE html><html><head><meta charset="utf-8"><title></title><style type="text/css">body{
 font-family: helvetica;
 color: #222;
}

li>p{
 margin-bottom: 0;
}

.line{
 margin-bottom: 0.3em;
 display: table;
}

.admonition-title {
    font-size: 1.3em;
    font-weight: bold;
}

aside{
 float: right;
 width: 20%;
 display: table;
 padding: 1em;
 margin: 1em;
 margin-right: 0;
}

.footnote, .cite{
 width: 98%;
 display: table;
 border: 1px solid #ddd;
 padding: 0.5%;
 margin: 0.5%;
}

.footnote .du-label, .cite .du-label{
 float: left;
 height: 100%;
 width: 5%;
 margin-right: 1em;
 padding: 0.5%;
 text-align: center;
 display: table;
}

th, th p{
 font-weight: bold;
}

.field-label{
 font-weight: bold;
}

ol.arabic{
 list-style-type: decimal;
}

ol.loweralpha{
 list-style-type: lower-alpha;
}

ol.upperalpha{
 list-style-type: upper-alpha;
}

ol.lowerroman{
 list-style-type: lower-roman;
}

ol.upperroman{
 list-style-type: upper-roman;
}

img.align-left{
 float: left;
}

img.align-right{
 float: right;
}
</style></head><body><p>d</p></body></html>

rst2html/templates/rst2html/uploadImagePage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Upload Image Page</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="
    <link rel="stylesheet" type="text/css" href="{% static 'rst2html/style.css' %}"/>
</head>
<body>
<div class="container">
    <h1>
        <ins>Upload Image Page</ins>
    </h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" name="pic" accept="image/*"><br>
        <button class="btn btn-primary btn-block" formaction="{% url 'rst2html:uploadImage' %}">Upload Image</button>
    </form>

</div>
</body>
</html>

rst2html/templates/rst2html/workpage.html
<!DOCTYPE html>


<html ng-app="app">
  <head>
    {% load staticfiles %}

    <script src="{%static 'rst2html/js/javascript.js' %}" type="text/javascript"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'rst2html/style.css' %}"
</head>
<body >

<h1 align="center">RST To HTML</h1>
<div id ="input">
<form style="text-align: center" >
<input type="text"  name="SlideName" placeholder="Enter a project name here"></input>
<select name="style">
    <option value=" ">clean</option>
    <option value="--deck-js --pretty-print-code --embed-content ">deck</option>
    <option value="--jquery --reveal-js --pretty-print-code ">reveal</option>
    <option value="--bootstrap-css --pretty-print-code --jquery --embed-content ">bootstrap</option>
 </select>
<input type="submit" value="Preview" formaction="{% url 'rst2html:Preview' %}" target="_blank"/>
<input type="submit" value="save" formaction="{% url 'rst2html:save' %}" />
<br/>	
<textarea id ="myTextBox"name="myTextBox" cols="150" rows="50" wrap ="off" placeholder="Enter a text here"></textarea>
for

</form>
</div>
<div id ="tools">

<form action="{% url 'rst2html:uploadImagePage' %}" style="display: inline;" target="_blank">
<input type="submit" value="Upload Image"></form>
<select id="imageselect">
{% for image in imagelist %}
<option value= {{ image }}> {{ image }}</option>
{% endfor %}

 </select>
<button onclick="insertAtCaret('myTextBox','.. image:: data/')">Add select image</button>
<form><input type="submit" value="clearUpload" formaction="{% url 'rst2html:clearUpload' %}" /></form>

</div>


</body>
</html>